# Welcome to Jekyll!
#

# Site settings
title: Eat your fertilizers, you'll grow up soon!
description:  |
  In the last decades, earth has been teaching us a simple lesson: "Nothing down here is infinite".  
  This pill seems hard to swallow for most agriculture systems, which keep on using more and more fertilizers and dreaming of infinite production.  
  Is this sustainable? Probably not.
owner: Team Ada_Nakamura # or company name
first_published: 20 Dec 2019 # if migrating another site, the year of your first publish
email: victor.rey@ens-lyon.fr
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
social:
  twitter: https://twitter.com/<username>
  github: https://github.com/<ReyVictor>
  linkedin-square: https://linkedin.com/in/<username>
  facebook-official: https://facebook.com/<username>
  google-plus-square: https://plus.google.com/u/0/+<username>
  #email: /contact/
  #flickr:
  #instagram:
  #youtube-square:
  #spotify:
  #stack-overflow:
  #vimeo:
  #reddit:
  #stubleupon:
  #delicious:
  #pied-piper:
  #digg:
  #soundcloud:
  #deviantart:
  #angellist:
  #tumblr-square:
  #stackexchange:
  #weibo:
  #trello:
  #foursquare:
  #linux:
  #bitbucket-square:
  #vk:
  #slack:
  #vine:
  #weixin:
  #yelp:
  #skyatlas:
  #leanpub:
  #connectdevelop:
  #ils:
  #forumbee:
  #tripadvisor:
  #amazon:

# Build settings
markdown: kramdown
#sass:
#  style: compressed

# theme                  : 
remote_theme: arkadianriver/spectral